In [21]:
A = dict()
B = dict()
C = dict()

A = {"a":0.2,"b":0.5,"c":0.6,"d":0.3}
B = {"a":0.8,"b":0.1,"c":0.4,"d":0.7}

In [22]:
print("The Fuzzy Set A is :",A)

The Fuzzy Set A is : {'a': 0.2, 'b': 0.5, 'c': 0.6, 'd': 0.3}


In [23]:
print("The Fuzzy Set B is :",B)

The Fuzzy Set B is : {'a': 0.8, 'b': 0.1, 'c': 0.4, 'd': 0.7}


# Union on Fuzzy Sets

In [24]:
for A_key,B_key in zip(A,B):
    A_value = A[A_key]
    B_value = B[B_key]
    
    if A_value > B_value:
        C[A_key] = A_value
    else:
        C[B_key] = B_value
print("Union of set A and B is :" , C)

Union of set A and B is : {'a': 0.8, 'b': 0.5, 'c': 0.6, 'd': 0.7}


In [25]:
import numpy as np
def fuzzy_union(A, B):
    return np.maximum(A, B)

In [26]:
x = np.array([0.2, 0.5, 0.6, 0.3])  # Fuzzy set A
y = np.array([0.8, 0.1, 0.4, 0.7])  # Fuzzy set B

In [27]:
print(fuzzy_union(x,y))

[0.8 0.5 0.6 0.7]


# Intersection on Fuzzy set

In [28]:
for A_key,B_key in zip(A,B):
    A_value = A[A_key]
    B_value = B[B_key]
    
    if A_value < B_value:
        C[A_key] = A_value
    else:
        C[B_key] = B_value
print("Intersection of Fuzzy Set A and B is :",C)

Intersection of Fuzzy Set A and B is : {'a': 0.2, 'b': 0.1, 'c': 0.4, 'd': 0.3}


In [32]:
def fuzzy_intersection(x,y):
    return np.minimum(x,y)

In [33]:
print(fuzzy_intersection(x,y))

[0.2 0.1 0.4 0.3]


# Complement

In [55]:
E = {"a":0.2,"b":0.2,"c":0.3,"d":0.5}

In [56]:
for E_key in E:
    C[E_key] = 1 - E[E_key]

In [57]:
print("Complement of E is : ",C)

Complement of E is :  {'a': 0.8, 'b': 0.8, 'c': 0.7, 'd': 0.5}


In [41]:
def fuzzy_complement(A):
    return 1 - A

In [58]:
E = np.array([0.2,0.2,0.7,0.5])

In [59]:
print(fuzzy_complement(E))

[0.8 0.8 0.3 0.5]


# Difference

In [64]:
A = {"a":0.2,"b":0.5,"c":0.6,"d":0.3}
B = {"a":0.8,"b":0.1,"c":0.4,"d":0.7}

In [65]:
for A_key, B_key in zip(A, B):
    A_value = A[A_key]
    B_value = B[B_key]
    B_value = 1 - B_value
 
    if A_value < B_value:
        C[A_key] = A_value
    else:
        C[B_key] = B_value
         
print('Fuzzy Set Difference is :', C)

Fuzzy Set Difference is : {'a': 0.19999999999999996, 'b': 0.5, 'c': 0.6, 'd': 0.3}


In [68]:
def fuzzy_difference(A, B):
    return np.maximum(A - B, 0)

In [69]:
print(fuzzy_difference(x, y))

[0.  0.4 0.2 0. ]


# creating fuzzy relations by Cartesian product of any two fuzzy sets 

In [70]:
def fuzzy_cartesian_product(x, y):
    # Reshape A and B to 1D arrays
    A_1D = A.flatten()
    B_1D = B.flatten()
    
    # Calculate Cartesian product
    cartesian_product = np.outer(A_1D, B_1D)
    
    return cartesian_product

In [73]:
x = np.array([0.2, 0.5, 0.6, 0.3])  # Fuzzy set A
y = np.array([0.8, 0.1, 0.4, 0.7])  # Fuzzy set B

In [74]:
print(fuzzy_cartesian_product(x, y))

[[0.16 0.02 0.08 0.14]
 [0.4  0.05 0.2  0.35]
 [0.48 0.06 0.24 0.42]
 [0.24 0.03 0.12 0.21]]


# perform max-min composition of two fuzzy relations

In [88]:
# Max-min composition on fuzzy relations
R = np.array([[0.2, 0.4],
              [0.3, 0.5]])  # Fuzzy relation R
S = np.array([[0.6, 0.8],
              [0.7, 0.9]])  # Fuzzy relation S

In [91]:
import numpy as np

# Function to perform max-min composition on two fuzzy relations
def max_min_composition(R, S):
    composition_matrix = np.zeros((len(R), len(S)))
    for i in range(len(R)):
        for j in range(len(S)):
            composition_matrix[i, j] = max(min(R[i, k], S[k, j]) for k in range(len(R)))
    return composition_matrix

# Example usage
R = np.array([[0.2, 0.4],
              [0.3, 0.5]])  # Fuzzy relation R
S = np.array([[0.6, 0.8],
              [0.7, 0.9]])  # Fuzzy relation S

composition_result = max_min_composition(R, S)
print("Max-min Composition of R and S:")
print(composition_result)


Max-min Composition of R and S:
[[0.4 0.4]
 [0.5 0.5]]
