In [2]:
A = dict()
B = dict()
C = dict()

In [3]:
A = {"a":1,"b":3,"c":5}
B = {"a":2,"b":7,"c":9}

In [4]:
import numpy as np

In [5]:
x = np.array([1,3,5])
y = np.array([2,7,9])

In [6]:
print("The fuzzy set of the A is ",A)


The fuzzy set of the A is  {'a': 1, 'b': 3, 'c': 5}


In [7]:
print("The fuzzy set of the B is ",B)

The fuzzy set of the B is  {'a': 2, 'b': 7, 'c': 9}


# Union

In [8]:
for A_Key,B_Key in zip(A,B):
    A_value = A[A_Key]
    B_value = B[B_Key]
    
    if A_value > B_value:
        C[A_key] = A_value
    else:
        C[A_Key] = B_value

print("Union of the A and B set is:",C)

Union of the A and B set is: {'a': 2, 'b': 7, 'c': 9}


In [9]:
def Fuzzy_Union(x,y):
    return np.maximum(x,y)
print("Union of the x and y set is:",Fuzzy_Union(x,y))

Union of the x and y set is: [2 7 9]


# Intersection

In [10]:
for A_Key,B_Key in zip(A,B):
    A_value = A[A_Key]
    B_value = B[B_Key]
    
    if A_value < B_value:
        C[A_Key] = A_value
    else:
        C[B_Key] = B_value

print("Intersection of the A and B set is:",C)  

Intersection of the A and B set is: {'a': 1, 'b': 3, 'c': 5}


In [11]:
def Fuzzy_intersection(A,B):
    return np.minimum(A,B)
print("Intersection of the x and y set is:",Fuzzy_intersection(x,y))

Intersection of the x and y set is: [1 3 5]


# Complement

In [12]:
for A_Key in A:
    C[A_Key] = 1 - C[A_Key]

print("Intersection of the set a is : ",C)

Intersection of the set a is :  {'a': 0, 'b': -2, 'c': -4}


In [13]:
def complement(x):
    return 1 - x
print("Intersection of the set x is : ",complement(x))

Intersection of the set x is :  [ 0 -2 -4]


# Difference

In [14]:
for A_Key,B_Key in zip(A,B):
    A_value = A[A_Key]
    B_value = B[B_Key]
    B_value = 1 - B_value
    
    if A_value < B_value:
        C[A_Key] = A_value
    else:
        C[B_Key] = B_value

print("Differnce of set A and B is  : ",C)

Differnce of set A and B is  :  {'a': -1, 'b': -6, 'c': -8}


In [15]:
def differ(x,y):
    return np.minimum(x,1-y)
print("Differnce of set x and y is :",differ(x,y))

Differnce of set x and y is : [-1 -6 -8]


# Cartesian Product

In [16]:

cartesian_product = []
for A_key, A_value in A.items():
    for B_key, B_value in B.items():
        cartesian_product.append(A_value * B_value)

print(cartesian_product)

[2, 7, 9, 6, 21, 27, 10, 35, 45]


In [17]:
# Function to create fuzzy relation by Cartesian product of two fuzzy sets
def cartesian_product(A, B):
  return np.outer(A, B)
print(cartesian_product(x,y))

[[ 2  7  9]
 [ 6 21 27]
 [10 35 45]]


# min max composition

In [48]:
A = {"a":1,"b":3}
B = {"a":2,"b":7}

In [49]:
def max_min_composition(A, B):
    composition_matrix = {}
    for a_key, a_value in A.items():
        composition_matrix[a_key] = {}
        for b_key, b_value in B.items():
            min_value = min(a_value, b_value)
            composition_matrix[a_key][b_key] = min_value
    return composition_matrix

print("Max-min Composition of A and B:",max_min_composition(A,B))


Max-min Composition of A and B: {'a': {'a': 1, 'b': 1}, 'b': {'a': 2, 'b': 3}}


In [22]:
x = np.array([1,3])
y = np.array([2,7])

In [24]:
import numpy as np

# Function to perform max-min composition on two fuzzy relations
def max_min_composition(R, S):
    composition_matrix = np.zeros((len(R), len(S)))
    for i in range(len(R)):
        for j in range(len(S)):
            composition_matrix[i, j] = max(min(R[i, k], S[k, j]) for k in range(len(R)))
    return composition_matrix

# Example usage
R = np.array([[0.2, 0.4],
              [0.3, 0.5]])  # Fuzzy relation R
S = np.array([[0.6, 0.8],
              [0.7, 0.9]])  # Fuzzy relation S

composition_result = max_min_composition(R, S)
print("Max-min Composition of R and S:")
print(composition_result)


Max-min Composition of R and S:
[[0.4 0.4]
 [0.5 0.5]]
